using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace WorkforceDataApi.Migrations
{
    /// <inheritdoc />
    public partial class AddEstablishmentRawTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "establishments_raw",
                columns: table => new
                {
                    urn = table.Column<string>(type: "VARCHAR", nullable: false),
                    lacode = table.Column<string>(name: "la_code", type: "VARCHAR", nullable: false),
                    laname = table.Column<string>(name: "la_name", type: "VARCHAR", nullable: false),
                    establishmentnumber = table.Column<string>(name: "establishment_number", type: "VARCHAR", nullable: true),
                    establishmentname = table.Column<string>(name: "establishment_name", type: "VARCHAR", nullable: false),
                    typeofestablishmentcode = table.Column<string>(name: "type_of_establishment_code", type: "VARCHAR", nullable: false),
                    typeofestablishmentname = table.Column<string>(name: "type_of_establishment_name", type: "VARCHAR", nullable: false),
                    establishmenttypegroupcode = table.Column<string>(name: "establishment_type_group_code", type: "VARCHAR", nullable: false),
                    establishmenttypegroupname = table.Column<string>(name: "establishment_type_group_name", type: "VARCHAR", nullable: false),
                    establishmentstatuscode = table.Column<string>(name: "establishment_status_code", type: "VARCHAR", nullable: false),
                    establishmentstatusname = table.Column<string>(name: "establishment_status_name", type: "VARCHAR", nullable: false),
                    reasonestablishmentopenedcode = table.Column<string>(name: "reason_establishment_opened_code", type: "VARCHAR", nullable: false),
                    reasonestablishmentopenedname = table.Column<string>(name: "reason_establishment_opened_name", type: "VARCHAR", nullable: true),
                    opendate = table.Column<string>(name: "open_date", type: "VARCHAR", nullable: true),
                    reasonestablishmentclosedcode = table.Column<string>(name: "reason_establishment_closed_code", type: "VARCHAR", nullable: false),
                    reasonestablishmentclosedname = table.Column<string>(name: "reason_establishment_closed_name", type: "VARCHAR", nullable: false),
                    closedate = table.Column<string>(name: "close_date", type: "VARCHAR", nullable: true),
                    phaseofeducationcode = table.Column<string>(name: "phase_of_education_code", type: "VARCHAR", nullable: false),
                    phaseofeducationname = table.Column<string>(name: "phase_of_education_name", type: "VARCHAR", nullable: false),
                    statutorylowage = table.Column<string>(name: "statutory_low_age", type: "VARCHAR", nullable: true),
                    statutoryhighage = table.Column<string>(name: "statutory_high_age", type: "VARCHAR", nullable: true),
                    boarderscode = table.Column<string>(name: "boarders_code", type: "VARCHAR", nullable: false),
                    boardersname = table.Column<string>(name: "boarders_name", type: "VARCHAR", nullable: true),
                    nurseryprovisionname = table.Column<string>(name: "nursery_provision_name", type: "VARCHAR", nullable: true),
                    officialsixthformcode = table.Column<string>(name: "official_sixth_form_code", type: "VARCHAR", nullable: false),
                    officialsixthformname = table.Column<string>(name: "official_sixth_form_name", type: "VARCHAR", nullable: true),
                    gendercode = table.Column<string>(name: "gender_code", type: "VARCHAR", nullable: false),
                    gendername = table.Column<string>(name: "gender_name", type: "VARCHAR", nullable: true),
                    religiouscharactercode = table.Column<string>(name: "religious_character_code", type: "VARCHAR", nullable: false),
                    religiouscharactername = table.Column<string>(name: "religious_character_name", type: "VARCHAR", nullable: true),
                    religiousethosname = table.Column<string>(name: "religious_ethos_name", type: "VARCHAR", nullable: true),
                    diocesecode = table.Column<string>(name: "diocese_code", type: "VARCHAR", nullable: false),
                    diocesename = table.Column<string>(name: "diocese_name", type: "VARCHAR", nullable: true),
                    admissionspolicycode = table.Column<string>(name: "admissions_policy_code", type: "VARCHAR", nullable: false),
                    admissionspolicyname = table.Column<string>(name: "admissions_policy_name", type: "VARCHAR", nullable: true),
                    schoolcapacity = table.Column<string>(name: "school_capacity", type: "VARCHAR", nullable: true),
                    specialclassescode = table.Column<string>(name: "special_classes_code", type: "VARCHAR", nullable: false),
                    specialclassesname = table.Column<string>(name: "special_classes_name", type: "VARCHAR", nullable: true),
                    censusdate = table.Column<string>(name: "census_date", type: "VARCHAR", nullable: true),
                    numberofpupils = table.Column<string>(name: "number_of_pupils", type: "VARCHAR", nullable: true),
                    numberofboys = table.Column<string>(name: "number_of_boys", type: "VARCHAR", nullable: true),
                    numberofgirls = table.Column<string>(name: "number_of_girls", type: "VARCHAR", nullable: true),
                    percentagefsm = table.Column<string>(name: "percentage_fsm", type: "VARCHAR", nullable: true),
                    trustschoolflagcode = table.Column<string>(name: "trust_school_flag_code", type: "VARCHAR", nullable: false),
                    trustschoolflagname = table.Column<string>(name: "trust_school_flag_name", type: "VARCHAR", nullable: false),
                    trustscode = table.Column<string>(name: "trusts_code", type: "VARCHAR", nullable: true),
                    trustsname = table.Column<string>(name: "trusts_name", type: "VARCHAR", nullable: true),
                    schoolsponsorflagname = table.Column<string>(name: "school_sponsor_flag_name", type: "VARCHAR", nullable: false),
                    schoolsponsorsname = table.Column<string>(name: "school_sponsors_name", type: "VARCHAR", nullable: false),
                    federationflagname = table.Column<string>(name: "federation_flag_name", type: "VARCHAR", nullable: false),
                    federationscode = table.Column<string>(name: "federations_code", type: "VARCHAR", nullable: true),
                    federationsname = table.Column<string>(name: "federations_name", type: "VARCHAR", nullable: true),
                    ukprn = table.Column<string>(type: "VARCHAR", nullable: true),
                    feheidentifier = table.Column<string>(name: "fehe_identifier", type: "VARCHAR", nullable: true),
                    furthereducationtypename = table.Column<string>(name: "further_education_type_name", type: "VARCHAR", nullable: true),
                    ofstedlastinsp = table.Column<string>(name: "ofsted_last_insp", type: "VARCHAR", nullable: true),
                    ofstedspecialmeasurescode = table.Column<string>(name: "ofsted_special_measures_code", type: "VARCHAR", nullable: false),
                    ofstedspecialmeasuresname = table.Column<string>(name: "ofsted_special_measures_name", type: "VARCHAR", nullable: false),
                    lastchangeddate = table.Column<string>(name: "last_changed_date", type: "VARCHAR", nullable: false),
                    street = table.Column<string>(type: "VARCHAR", nullable: true),
                    locality = table.Column<string>(type: "VARCHAR", nullable: true),
                    address3 = table.Column<string>(type: "VARCHAR", nullable: true),
                    town = table.Column<string>(type: "VARCHAR", nullable: true),
                    countyname = table.Column<string>(name: "county_name", type: "VARCHAR", nullable: true),
                    postcode = table.Column<string>(type: "VARCHAR", nullable: true),
                    schoolwebsite = table.Column<string>(name: "school_website", type: "VARCHAR", nullable: true),
                    telephonenum = table.Column<string>(name: "telephone_num", type: "VARCHAR", nullable: true),
                    headtitlename = table.Column<string>(name: "head_title_name", type: "VARCHAR", nullable: true),
                    headfirstname = table.Column<string>(name: "head_first_name", type: "VARCHAR", nullable: true),
                    headlastname = table.Column<string>(name: "head_last_name", type: "VARCHAR", nullable: true),
                    headpreferredjobtitle = table.Column<string>(name: "head_preferred_job_title", type: "VARCHAR", nullable: true),
                    bsoinspectoratenamename = table.Column<string>(name: "bso_inspectorate_name_name", type: "VARCHAR", nullable: false),
                    inspectoratereport = table.Column<string>(name: "inspectorate_report", type: "VARCHAR", nullable: true),
                    dateoflastinspectionvisit = table.Column<string>(name: "date_of_last_inspection_visit", type: "VARCHAR", nullable: true),
                    nextinspectionvisit = table.Column<string>(name: "next_inspection_visit", type: "VARCHAR", nullable: true),
                    teenmothname = table.Column<string>(name: "teen_moth_name", type: "VARCHAR", nullable: true),
                    teenmothplaces = table.Column<string>(name: "teen_moth_places", type: "VARCHAR", nullable: true),
                    ccfname = table.Column<string>(name: "ccf_name", type: "VARCHAR", nullable: true),
                    senpruname = table.Column<string>(name: "sen_pru_name", type: "VARCHAR", nullable: true),
                    ebdname = table.Column<string>(name: "ebd_name", type: "VARCHAR", nullable: true),
                    placespru = table.Column<string>(name: "places_pru", type: "VARCHAR", nullable: true),
                    ftprovname = table.Column<string>(name: "ft_prov_name", type: "VARCHAR", nullable: true),
                    edbyothername = table.Column<string>(name: "ed_by_other_name", type: "VARCHAR", nullable: true),
                    section41approvedname = table.Column<string>(name: "section41approved_name", type: "VARCHAR", nullable: false),
                    sen1name = table.Column<string>(type: "VARCHAR", nullable: true),
                    sen2name = table.Column<string>(type: "VARCHAR", nullable: true),
                    sen3name = table.Column<string>(type: "VARCHAR", nullable: true),
                    sen4name = table.Column<string>(type: "VARCHAR", nullable: true),
                    sen5name = table.Column<string>(type: "VARCHAR", nullable: true),
                    sen6name = table.Column<string>(type: "VARCHAR", nullable: true),
                    sen7name = table.Column<string>(type: "VARCHAR", nullable: true),
                    sen8name = table.Column<string>(type: "VARCHAR", nullable: true),
                    sen9name = table.Column<string>(type: "VARCHAR", nullable: true),
                    sen10name = table.Column<string>(type: "VARCHAR", nullable: true),
                    sen11name = table.Column<string>(type: "VARCHAR", nullable: true),
                    sen12name = table.Column<string>(type: "VARCHAR", nullable: true),
                    sen13name = table.Column<string>(type: "VARCHAR", nullable: true),
                    typeofresourcedprovisionname = table.Column<string>(name: "type_of_resourced_provision_name", type: "VARCHAR", nullable: true),
                    resourcedprovisiononroll = table.Column<string>(name: "resourced_provision_on_roll", type: "VARCHAR", nullable: true),
                    resourcedprovisioncapacity = table.Column<string>(name: "resourced_provision_capacity", type: "VARCHAR", nullable: true),
                    senunitonroll = table.Column<string>(name: "sen_unit_on_roll", type: "VARCHAR", nullable: true),
                    senunitcapacity = table.Column<string>(name: "sen_unit_capacity", type: "VARCHAR", nullable: true),
                    gorcode = table.Column<string>(name: "gor_code", type: "VARCHAR", nullable: false),
                    gorname = table.Column<string>(name: "gor_name", type: "VARCHAR", nullable: false),
                    districtadministrativecode = table.Column<string>(name: "district_administrative_code", type: "VARCHAR", nullable: false),
                    districtadministrativename = table.Column<string>(name: "district_administrative_name", type: "VARCHAR", nullable: true),
                    administrativewardcode = table.Column<string>(name: "administrative_ward_code", type: "VARCHAR", nullable: false),
                    administrativewardname = table.Column<string>(name: "administrative_ward_name", type: "VARCHAR", nullable: true),
                    parliamentaryconstituencycode = table.Column<string>(name: "parliamentary_constituency_code", type: "VARCHAR", nullable: false),
                    parliamentaryconstituencyname = table.Column<string>(name: "parliamentary_constituency_name", type: "VARCHAR", nullable: true),
                    urbanruralcode = table.Column<string>(name: "urban_rural_code", type: "VARCHAR", nullable: false),
                    urbanruralname = table.Column<string>(name: "urban_rural_name", type: "VARCHAR", nullable: true),
                    gsslacodename = table.Column<string>(name: "gss_la_code_name", type: "VARCHAR", nullable: false),
                    easting = table.Column<string>(type: "VARCHAR", nullable: true),
                    northing = table.Column<string>(type: "VARCHAR", nullable: true),
                    msoaname = table.Column<string>(name: "msoa_name", type: "VARCHAR", nullable: true),
                    lsoaname = table.Column<string>(name: "lsoa_name", type: "VARCHAR", nullable: true),
                    inspectoratenamename = table.Column<string>(name: "inspectorate_name_name", type: "VARCHAR", nullable: true),
                    senstat = table.Column<string>(name: "sen_stat", type: "VARCHAR", nullable: true),
                    sennostat = table.Column<string>(name: "sen_no_stat", type: "VARCHAR", nullable: true),
                    boardingestablishmentname = table.Column<string>(name: "boarding_establishment_name", type: "VARCHAR", nullable: true),
                    propsname = table.Column<string>(name: "props_name", type: "VARCHAR", nullable: true),
                    previouslacode = table.Column<string>(name: "previous_la_code", type: "VARCHAR", nullable: false),
                    previouslaname = table.Column<string>(name: "previous_la_name", type: "VARCHAR", nullable: true),
                    previousestablishmentnumber = table.Column<string>(name: "previous_establishment_number", type: "VARCHAR", nullable: true),
                    ofstedratingname = table.Column<string>(name: "ofsted_rating_name", type: "VARCHAR", nullable: true),
                    rscregionname = table.Column<string>(name: "rsc_region_name", type: "VARCHAR", nullable: true),
                    countryname = table.Column<string>(name: "country_name", type: "VARCHAR", nullable: true),
                    uprn = table.Column<string>(type: "VARCHAR", nullable: true),
                    sitename = table.Column<string>(name: "site_name", type: "VARCHAR", nullable: true),
                    qabnamecode = table.Column<string>(name: "qab_name_code", type: "VARCHAR", nullable: true),
                    qabnamename = table.Column<string>(name: "qab_name_name", type: "VARCHAR", nullable: true),
                    establishmentaccreditedcode = table.Column<string>(name: "establishment_accredited_code", type: "VARCHAR", nullable: true),
                    establishmentaccreditedname = table.Column<string>(name: "establishment_accredited_name", type: "VARCHAR", nullable: true),
                    qabreport = table.Column<string>(name: "qab_report", type: "VARCHAR", nullable: true),
                    chnumber = table.Column<string>(name: "ch_number", type: "VARCHAR", nullable: true),
                    msoacode = table.Column<string>(name: "msoa_code", type: "VARCHAR", nullable: false),
                    lsoacode = table.Column<string>(name: "lsoa_code", type: "VARCHAR", nullable: false),
                    fsm = table.Column<string>(type: "VARCHAR", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_establishments_raw", x => x.urn);
                });

            migrationBuilder.CreateIndex(
                name: "ix_establishment_raw_establishment_number",
                table: "establishments_raw",
                column: "establishment_number");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "establishments_raw");
        }
    }
}
