// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkforceDataApi.Models;

#nullable disable

namespace WorkforceDataApi.Migrations
{
    [DbContext(typeof(WorkforceDbContext))]
    partial class WorkforceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:CollationDefinition:case_insensitive", "und-u-ks-level2,und-u-ks-level2,icu,False")
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkforceDataApi.Models.TpsExtractDataItem", b =>
                {
                    b.Property<string>("TpsExtractDataItemId")
                        .HasColumnType("text")
                        .HasColumnName("tps_extract_data_item_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email_address")
                        .UseCollation("case_insensitive");

                    b.Property<DateOnly>("EmploymentPeriodEndDate")
                        .HasColumnType("date")
                        .HasColumnName("employment_period_end_date");

                    b.Property<DateOnly>("EmploymentPeriodStartDate")
                        .HasColumnType("date")
                        .HasColumnName("employment_period_start_date");

                    b.Property<string>("EstablishmentNumber")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character(4)")
                        .HasColumnName("establishment_number")
                        .IsFixedLength();

                    b.Property<string>("EstablishmentPostcode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("establishment_postcode");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("first_name");

                    b.Property<int>("FullOrPartTimeIndicator")
                        .HasColumnType("integer")
                        .HasColumnName("full_or_part_time_indicator");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_name");

                    b.Property<string>("LocalAuthorityNumber")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("local_authority_number")
                        .IsFixedLength();

                    b.Property<string>("MemberPostcode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("member_postcode");

                    b.Property<string>("Nino")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character(9)")
                        .HasColumnName("nino")
                        .IsFixedLength();

                    b.Property<string>("TeachingStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasColumnName("teaching_status")
                        .IsFixedLength();

                    b.Property<string>("Trn")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character(7)")
                        .HasColumnName("trn")
                        .IsFixedLength();

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated");

                    b.HasKey("TpsExtractDataItemId")
                        .HasName("pk_tps_extract_data_item");

                    b.HasIndex("Trn")
                        .HasDatabaseName("ix_tps_extract_data_item_trn");

                    b.ToTable("tps_extract_data_item", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
